apiVersion: v1
kind: Secret
metadata:
  name: myapp-secrets
  namespace: myapp
type: Opaque
data:
  db-root-password: cm9vdHBhc3N3b3Jk    # 'rootpassword'
  db-name: bXlkYg==                    # 'mydb'
  db-user: cm9vdA==                    # 'root'
  # optionally: docker/registry creds if using imagePullSecrets
